from pathlib import Path

path = Path('uralla_build/source.py')
text = path.read_text(encoding='utf-8')

old = '''_DOWNLOAD_ATTEMPTS = 4\n_DOWNLOAD_BACKOFF_SECONDS = (5, 15, 30)\n'''
new = '''_DOWNLOAD_ATTEMPTS = 4\n_DOWNLOAD_BACKOFF_SECONDS = (5, 15, 30)\n_DOWNLOAD_TIMEOUT_SECONDS = 300\n_DOWNLOAD_READ_BLOCK = 1 * _MIB\n'''
assert old in text
text = text.replace(old, new, 1)

old = '''def _progress_interval(expected: int | None) -> int:\n    \"\"\"Report small downloads too, while keeping multi-GiB downloads readable.\"\"\"\n\n    if expected is None:\n        return 64 * _MIB\n    return min(256 * _MIB, max(8 * _MIB, expected // 20))\n\n\ndef _download_once(url: str, target: Path) -> None:\n    with urlopen(url, timeout=300) as response, target.open(\"wb\") as output:\n        raw_length = response.headers.get(\"Content-Length\")\n        expected = int(raw_length) if raw_length and raw_length.isdigit() else None\n        if expected is not None:\n            _log(f\"remote size: {_format_size(expected)}\")\n        else:\n            _log(\"remote size: unknown\")\n\n        copied = 0\n        interval = _progress_interval(expected)\n        next_report = interval\n        while True:\n            block = response.read(8 * _MIB)\n            if not block:\n                break\n            output.write(block)\n            copied += len(block)\n            if copied >= next_report:\n                if expected:\n                    percent = min(100.0, copied * 100.0 / expected)\n                    _log(\n                        f\"downloaded {_format_size(copied)} / {_format_size(expected)} \"\n                        f\"({percent:.1f}%)\"\n                    )\n                else:\n                    _log(f\"downloaded {_format_size(copied)}\")\n                while next_report <= copied:\n                    next_report += interval\n        output.flush()\n        os.fsync(output.fileno())\n\n    if expected is not None and copied != expected:\n        raise StageError(\n            f\"source download size mismatch: expected {expected} bytes, received {copied}\"\n        )\n    if copied == 0:\n        raise StageError(\"source download is empty\")\n    _log(f\"download complete: {_format_size(copied)}\")\n'''
new = '''def _progress_interval(expected: int | None) -> int:\n    \"\"\"Report small downloads too, while keeping multi-GiB downloads readable.\"\"\"\n\n    if expected is None:\n        return 64 * _MIB\n    return min(256 * _MIB, max(4 * _MIB, expected // 20))\n\n\ndef _download_once(url: str, target: Path) -> None:\n    connect_started = time.monotonic()\n    _log(f\"connecting; server-response timeout {_DOWNLOAD_TIMEOUT_SECONDS} s\")\n    with urlopen(url, timeout=_DOWNLOAD_TIMEOUT_SECONDS) as response, target.open(\"wb\") as output:\n        connected_after = time.monotonic() - connect_started\n        raw_length = response.headers.get(\"Content-Length\")\n        expected = int(raw_length) if raw_length and raw_length.isdigit() else None\n        if expected is not None:\n            _log(f\"connected in {connected_after:.1f} s; remote size: {_format_size(expected)}\")\n        else:\n            _log(f\"connected in {connected_after:.1f} s; remote size: unknown\")\n\n        copied = 0\n        download_started = time.monotonic()\n        interval = _progress_interval(expected)\n        next_report = interval\n        while True:\n            block = response.read(_DOWNLOAD_READ_BLOCK)\n            if not block:\n                break\n            output.write(block)\n            copied += len(block)\n            if copied >= next_report:\n                elapsed = max(time.monotonic() - download_started, 0.001)\n                rate = copied / elapsed\n                if expected:\n                    percent = min(100.0, copied * 100.0 / expected)\n                    _log(\n                        f\"downloaded {_format_size(copied)} / {_format_size(expected)} \"\n                        f\"({percent:.1f}%); {_format_size(int(rate))}/s\"\n                    )\n                else:\n                    _log(f\"downloaded {_format_size(copied)}; {_format_size(int(rate))}/s\")\n                while next_report <= copied:\n                    next_report += interval\n        output.flush()\n        os.fsync(output.fileno())\n\n    if expected is not None and copied != expected:\n        raise StageError(\n            f\"source download size mismatch: expected {expected} bytes, received {copied}\"\n        )\n    if copied == 0:\n        raise StageError(\"source download is empty\")\n    elapsed = max(time.monotonic() - download_started, 0.001)\n    rate = copied / elapsed\n    _log(\n        f\"download complete: {_format_size(copied)} in {elapsed:.1f} s; \"\n        f\"avg {_format_size(int(rate))}/s\"\n    )\n'''
assert old in text
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
