from pathlib import Path

LINES = Path('styles/uralla/lines')
text = LINES.read_text(encoding='utf-8')

old_ped = '''# Some countries allow, others disallow bicycling on pedestrian streets.\nhighway=pedestrian & area!=yes [0x07 road_class=0 road_speed=0 resolution 22-23 continue]\nhighway=pedestrian & area!=yes [0x0e road_class=0 road_speed=0 resolution 24]\n\nhighway=living_street [0x06 road_class=0 road_speed=1 resolution 23]\n\n# [CUSTOM/АВТОРСКОЕ] Marked route members are shown one level farther out than\n# ordinary ways of the same class. At that extra level use the close-zoom line\n# type, making the route visually stronger without introducing new graphics.\nmkgmap:trail_name=* & highway=pedestrian & area!=yes & length()>100 [0x0e resolution 21-21 continue]\nmkgmap:trail_name=* & highway=cycleway & length()>100 [0x0e resolution 21-21 continue]\nmkgmap:trail_name=* & bicycle=yes & highway=path & length()>100 [0x16 resolution 21-21 continue]\nmkgmap:trail_name=* & highway=footway & length()>100 [0x0e resolution 21-21 continue]\nmkgmap:trail_name=* & bicycle!=yes & highway=path & length()>100 [0x16 resolution 22-22 continue]\nmkgmap:trail_name=* & highway=track & tracktype!=grade1 & length()>100 [0x13 resolution 21-21 continue]\nmkgmap:trail_name=* & highway=track & tracktype=grade1 & length()>100 [0x0a resolution 20-20 continue]\nmkgmap:trail_name=* & highway=bridleway & length()>100 [0x16 resolution 23-23 continue]\n'''

new_ped = '''# [CUSTOM/АВТОРСКОЕ] Marked route members switch to the close-zoom line one\n# level earlier and keep that same visual continuously through resolution 24.\n# These rules must stay before all base pedestrian/path/track rules: they own\n# marked ways completely, avoiding the old near -> far -> near sandwich.\nmkgmap:trail_name=* & highway=pedestrian & area!=yes & length()>100 [0x0e road_class=0 road_speed=0 resolution 21-24]\nmkgmap:trail_name=* & highway=cycleway & length()>100 [0x0e road_class=0 road_speed=1 resolution 21-24]\nmkgmap:trail_name=* & bicycle=yes & highway=path & length()>100 [0x16 road_class=0 road_speed=1 resolution 21-24]\nmkgmap:trail_name=* & highway=footway & length()>100 [0x0e road_class=0 road_speed=1 resolution 21-24]\nmkgmap:trail_name=* & bicycle!=yes & highway=path & length()>100 [0x16 road_class=0 road_speed=0 resolution 22-24]\nmkgmap:trail_name=* & highway=track & tracktype!=grade1 & length()>100 [0x13 road_class=0 road_speed=1 resolution 21-24]\nmkgmap:trail_name=* & highway=track & tracktype=grade1 & length()>100 [0x0a road_class=0 road_speed=1 resolution 20-24]\nmkgmap:trail_name=* & highway=bridleway & length()>100 [0x16 road_class=0 road_speed=0 resolution 23-24]\n\n# Some countries allow, others disallow bicycling on pedestrian streets.\nhighway=pedestrian & area!=yes [0x07 road_class=0 road_speed=0 resolution 22-23 continue]\nhighway=pedestrian & area!=yes [0x0e road_class=0 road_speed=0 resolution 24]\n\nhighway=living_street [0x06 road_class=0 road_speed=1 resolution 23]\n'''

if old_ped not in text:
    raise SystemExit('marked/pedestrian block not found exactly')
text = text.replace(old_ped, new_ped, 1)
LINES.write_text(text, encoding='utf-8', newline='\n')
print('removed marked-route near/far/near sandwich')
