.level=WARNING
handlers=java.util.logging.FileHandler java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=WARNING
java.util.logging.ConsoleHandler.formatter=uk.me.parabola.log.UsefulFormatter

java.util.logging.FileHandler.level=FINE
java.util.logging.FileHandler.encoding=UTF-8
java.util.logging.FileHandler.formatter=uk.me.parabola.log.UsefulFormatter
java.util.logging.FileHandler.limit=50000000
java.util.logging.FileHandler.count=2
java.util.logging.FileHandler.pattern=mkgmap-debug.log
java.util.logging.FileHandler.append=false

uk.me.parabola.mkgmap.main.level=FINE
uk.me.parabola.mkgmap.combiners.level=FINE
uk.me.parabola.imgfmt.level=FINE
