from pathlib import Path

priority = Path('styles/uralla/inc/priority_points')
s = priority.read_text(encoding='utf-8')

old = """# Grocery group. Final adaptive visibility is consumed from uralla:poi_lod_class,\n# produced by the preprocessor from rarity + activity context + screen pressure +\n# intrinsic category floor. Temporary visual suffixes expose the actual final class.\n# Untagged fallbacks preserve legacy safety: supermarkets=23, other groceries=24.\nuralla:poi_lod_class=H & (shop=supermarket | amenity=supermarket | shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name} [H]' | '[H]' } [0x2e02 resolution 22]\nuralla:poi_lod_class=M & (shop=supermarket | amenity=supermarket | shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name} [M]' | '[M]' } [0x2e02 resolution 23]\nuralla:poi_lod_class=L & (shop=supermarket | amenity=supermarket | shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name} [L]' | '[L]' } [0x2e02 resolution 24]\n(shop=supermarket | amenity=supermarket) { name '${name} [M]' | '[M]' } [0x2e02 resolution 23]\n(shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name} [L]' | '[L]' } [0x2e02 resolution 24]\n"""
new = """# Grocery group. Final adaptive visibility is consumed from uralla:poi_lod_class,\n# produced by the preprocessor from rarity + activity context + screen pressure +\n# intrinsic category floor. Untagged fallbacks preserve legacy safety:\n# supermarkets=23, other groceries=24.\n# Unnamed convenience shops stay visually unlabeled but expose \"магазинчик\" on hover.\nuralla:poi_lod_class=H & shop=convenience & name!=* { set mkgmap:label:1=' '; set mkgmap:label:2='магазинчик' } [0x2e02 resolution 22]\nuralla:poi_lod_class=M & shop=convenience & name!=* { set mkgmap:label:1=' '; set mkgmap:label:2='магазинчик' } [0x2e02 resolution 23]\nuralla:poi_lod_class=L & shop=convenience & name!=* { set mkgmap:label:1=' '; set mkgmap:label:2='магазинчик' } [0x2e02 resolution 24]\nuralla:poi_lod_class=H & (shop=supermarket | amenity=supermarket | shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name}' } [0x2e02 resolution 22]\nuralla:poi_lod_class=M & (shop=supermarket | amenity=supermarket | shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name}' } [0x2e02 resolution 23]\nuralla:poi_lod_class=L & (shop=supermarket | amenity=supermarket | shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name}' } [0x2e02 resolution 24]\nshop=convenience & name!=* { set mkgmap:label:1=' '; set mkgmap:label:2='магазинчик' } [0x2e02 resolution 24]\n(shop=supermarket | amenity=supermarket) { name '${name}' } [0x2e02 resolution 23]\n(shop=bakers | shop=bakery | shop=butcher | shop=convenience | shop=general | shop=grocery | shop=organic) { name '${name}' } [0x2e02 resolution 24]\n"""
assert old in s, 'grocery block not found'
s = s.replace(old, new, 1)

old = """# Tourist accommodation / shelters. Adaptive visibility consumes final LOD class.\nuralla:poi_lod_class=H & tourism=guest_house { name '${name} [H]' | '[H]' } [0x2b01 resolution 22]\nuralla:poi_lod_class=M & tourism=guest_house { name '${name} [M]' | '[M]' } [0x2b01 resolution 23]\nuralla:poi_lod_class=L & tourism=guest_house { name '${name} [L]' | '[L]' } [0x2b01 resolution 24]\ntourism=guest_house { name '${name} [L]' | '[L]' } [0x2b01 resolution 24]\nuralla:poi_lod_class=H & tourism=hotel { name '${name} [H]' | '[H]' } [0x2b01 resolution 22]\nuralla:poi_lod_class=M & tourism=hotel { name '${name} [M]' | '[M]' } [0x2b01 resolution 23]\nuralla:poi_lod_class=L & tourism=hotel { name '${name} [L]' | '[L]' } [0x2b01 resolution 24]\ntourism=hotel { name '${name} [L]' | '[L]' } [0x2b01 resolution 24]\ntourism=motel [0x2b01 resolution 24]\nuralla:poi_lod_class=H & tourism=hostel { name '${name} [H]' | '[H]' } [0x2b02 resolution 22]\nuralla:poi_lod_class=M & tourism=hostel { name '${name} [M]' | '[M]' } [0x2b02 resolution 23]\nuralla:poi_lod_class=L & tourism=hostel { name '${name} [L]' | '[L]' } [0x2b02 resolution 24]\ntourism=hostel { name '${name} [L]' | '[L]' } [0x2b02 resolution 24]\n"""
new = """# Tourist accommodation / shelters. Adaptive visibility consumes final LOD class.\nuralla:poi_lod_class=H & tourism=guest_house { name '${name}' } [0x2b01 resolution 22]\nuralla:poi_lod_class=M & tourism=guest_house { name '${name}' } [0x2b01 resolution 23]\nuralla:poi_lod_class=L & tourism=guest_house { name '${name}' } [0x2b01 resolution 24]\ntourism=guest_house { name '${name}' } [0x2b01 resolution 24]\nuralla:poi_lod_class=H & tourism=hotel { name '${name}' } [0x2b01 resolution 22]\nuralla:poi_lod_class=M & tourism=hotel { name '${name}' } [0x2b01 resolution 23]\nuralla:poi_lod_class=L & tourism=hotel { name '${name}' } [0x2b01 resolution 24]\ntourism=hotel { name '${name}' } [0x2b01 resolution 24]\ntourism=motel [0x2b01 resolution 24]\nuralla:poi_lod_class=H & tourism=hostel { name '${name}' } [0x2b02 resolution 22]\nuralla:poi_lod_class=M & tourism=hostel { name '${name}' } [0x2b02 resolution 23]\nuralla:poi_lod_class=L & tourism=hostel { name '${name}' } [0x2b02 resolution 24]\ntourism=hostel { name '${name}' } [0x2b02 resolution 24]\n"""
assert old in s, 'accommodation block not found'
priority.write_text(s.replace(old, new, 1), encoding='utf-8')

points = Path('styles/uralla/points')
s = points.read_text(encoding='utf-8')
old = """uralla:poi_lod_class=H & (highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name} [H]' | '[H]' } [0x2f08 resolution 22]\nuralla:poi_lod_class=M & (highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name} [M]' | '[M]' } [0x2f08 resolution 23]\nuralla:poi_lod_class=L & (highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name} [L]' | '[L]' } [0x2f08 resolution 24]\n(highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name} [L]' | '[L]' } [0x2f08 resolution 24]\n"""
new = """uralla:poi_lod_class=H & (highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name}' } [0x2f08 resolution 22]\nuralla:poi_lod_class=M & (highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name}' } [0x2f08 resolution 23]\nuralla:poi_lod_class=L & (highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name}' } [0x2f08 resolution 24]\n(highway=bus_stop | public_transport=platform & (bus=yes | trolleybus=yes)) & mkgmap:area2poi!=true { name '${name}' } [0x2f08 resolution 24]\n"""
assert old in s, 'transit block not found'
points.write_text(s.replace(old, new, 1), encoding='utf-8')
