<?php
/**
 * Plugin Name: Garmin OSM Topo — Map Status
 * Description: Shortcode [garmin_map_status] for the public Garmin map download/status block.
 * Version: 1.0.0
 */

if (!defined('ABSPATH')) {
    exit;
}

const URALLA_GARMIN_STATUS_URL = 'https://www.uralla.ru/garmin.img/map-update-status.json';
const URALLA_GARMIN_FILES_BASE = 'https://www.uralla.ru/garmin.img/';
const URALLA_GARMIN_GITHUB_URL = 'https://github.com/uralla/OSM-Topo';

function uralla_garmin_status_fetch() {
    $cache_key = 'uralla_garmin_map_status_v1';
    $cached = get_transient($cache_key);

    if (is_array($cached)) {
        return $cached;
    }

    $response = wp_safe_remote_get(URALLA_GARMIN_STATUS_URL, [
        'timeout'     => 8,
        'redirection' => 2,
        'headers'     => [
            'Accept' => 'application/json',
        ],
    ]);

    if (is_wp_error($response)) {
        return $response;
    }

    $code = wp_remote_retrieve_response_code($response);
    if ($code !== 200) {
        return new WP_Error('garmin_status_http', 'HTTP ' . $code);
    }

    $body = wp_remote_retrieve_body($response);
    $data = json_decode($body, true);

    if (
        !is_array($data) ||
        !isset($data['products']) ||
        !is_array($data['products'])
    ) {
        return new WP_Error('garmin_status_json', 'Некорректный JSON статуса карт.');
    }

    // Short cache: status is regenerated by the build daemon, so WordPress
    // should not hammer the JSON file on every page view.
    set_transient($cache_key, $data, 60);

    return $data;
}

function uralla_garmin_status_url($relative) {
    if (!is_string($relative) || $relative === '') {
        return '';
    }

    if (preg_match('~^https?://~i', $relative)) {
        return $relative;
    }

    return trailingslashit(URALLA_GARMIN_FILES_BASE) . ltrim($relative, '/');
}

function uralla_garmin_status_date($value) {
    if (!is_string($value) || $value === '') {
        return '';
    }

    try {
        $dt = new DateTimeImmutable($value);
        return wp_date('d.m.Y H:i', $dt->getTimestamp(), wp_timezone());
    } catch (Exception $e) {
        return '';
    }
}

function uralla_garmin_status_size($bytes) {
    if (!is_numeric($bytes) || (float) $bytes <= 0) {
        return '';
    }

    return size_format((int) $bytes, 1);
}

function uralla_garmin_status_state($state) {
    $states = [
        'current' => ['icon' => '🟢', 'label' => 'актуальна', 'class' => 'is-current'],
        'due' => ['icon' => '🟡', 'label' => 'ожидает обновления', 'class' => 'is-due'],
        'building' => ['icon' => '🔵', 'label' => 'собирается', 'class' => 'is-building'],
        'error' => ['icon' => '🔴', 'label' => 'ошибка', 'class' => 'is-error'],
        'interrupted' => ['icon' => '🔴', 'label' => 'сборка прервана', 'class' => 'is-error'],
        'unknown' => ['icon' => '⚪', 'label' => 'статус неизвестен', 'class' => 'is-unknown'],
    ];

    return $states[$state] ?? $states['unknown'];
}

function uralla_garmin_download_button($artifact, $label) {
    $available = is_array($artifact) && !empty($artifact['available']);
    $url = $available ? uralla_garmin_status_url($artifact['url'] ?? '') : '';
    $size = $available ? uralla_garmin_status_size($artifact['size'] ?? null) : '';

    if (!$available || $url === '') {
        return sprintf(
            '<span class="garmin-map-btn is-disabled" aria-disabled="true">%s</span>',
            esc_html($label)
        );
    }

    $text = $size !== '' ? $label . ' · ' . $size : $label;

    return sprintf(
        '<a class="garmin-map-btn" href="%s">%s</a>',
        esc_url($url),
        esc_html($text)
    );
}

function uralla_garmin_map_status_shortcode() {
    $data = uralla_garmin_status_fetch();

    ob_start();
    ?>
    <section class="garmin-map-status">
        <?php if (is_wp_error($data)) : ?>
            <div class="garmin-map-status-error">
                Не удалось получить текущий статус карт.
                <a href="<?php echo esc_url(URALLA_GARMIN_FILES_BASE); ?>">Открыть каталог файлов</a>
            </div>
        <?php else : ?>
            <div class="garmin-map-status-head">
                <div>
                    <h2>Скачать карты Garmin</h2>
                    <p>Готовые карты остаются доступными и во время сборки следующей версии.</p>
                </div>
                <?php
                $generated = uralla_garmin_status_date($data['generated_at'] ?? '');
                if ($generated !== '') :
                ?>
                    <div class="garmin-map-generated">
                        Статус обновлён<br>
                        <strong><?php echo esc_html($generated); ?></strong>
                    </div>
                <?php endif; ?>
            </div>

            <div class="garmin-map-legend" aria-label="Обозначения статусов">
                <span>🟢 актуальна</span>
                <span>🟡 ожидает обновления</span>
                <span>🔵 собирается</span>
                <span>🔴 ошибка</span>
                <span>⚠️ собрана предыдущей версией</span>
            </div>

            <div class="garmin-map-grid">
                <?php foreach ($data['products'] as $product) :
                    if (!is_array($product)) {
                        continue;
                    }

                    $title = (string) ($product['title'] ?? $product['product'] ?? 'Карта');
                    $state = uralla_garmin_status_state((string) ($product['state'] ?? 'unknown'));
                    $recipe_state = isset($product['recipe_state']) ? (string) $product['recipe_state'] : '';
                    $recipe_old = in_array($recipe_state, ['stale', 'legacy'], true);

                    $last = uralla_garmin_status_date($product['last_publication'] ?? '');
                    $next = uralla_garmin_status_date($product['next_update'] ?? '');
                    $never = !empty($product['never_built']);

                    $img = is_array($product['img'] ?? null) ? $product['img'] : [];
                    $basecamp = is_array($product['basecamp'] ?? null) ? $product['basecamp'] : [];
                ?>
                    <article class="garmin-map-card <?php echo esc_attr($state['class']); ?>">
                        <div class="garmin-map-card-top">
                            <h3>
                                <?php echo esc_html($title); ?>
                                <?php if ($recipe_old) : ?>
                                    <span class="garmin-map-recipe-warning"
                                          title="Карта собрана предыдущей версией стиля или алгоритмов"
                                          aria-label="Собрана предыдущей версией">⚠️</span>
                                <?php endif; ?>
                            </h3>
                            <div class="garmin-map-state">
                                <span aria-hidden="true"><?php echo esc_html($state['icon']); ?></span>
                                <?php echo esc_html($state['label']); ?>
                            </div>
                        </div>

                        <div class="garmin-map-meta">
                            <?php if ($never) : ?>
                                <span>Первая публикация ещё не завершена</span>
                            <?php elseif ($last !== '') : ?>
                                <span>Текущая версия: <strong><?php echo esc_html($last); ?></strong></span>
                            <?php endif; ?>

                            <?php if ($next !== '') : ?>
                                <span>Следующее обновление ≈ <strong><?php echo esc_html($next); ?></strong></span>
                            <?php elseif ($never) : ?>
                                <span>Ожидает первой сборки</span>
                            <?php endif; ?>
                        </div>

                        <?php if ($recipe_old) : ?>
                            <div class="garmin-map-recipe-note">
                                ⚠️ Карта рабочая, но собрана предыдущей версией стиля/алгоритмов.
                            </div>
                        <?php endif; ?>

                        <div class="garmin-map-actions">
                            <?php echo uralla_garmin_download_button($img, 'Скачать IMG'); ?>
                            <?php echo uralla_garmin_download_button($basecamp, 'BaseCamp'); ?>
                        </div>
                    </article>
                <?php endforeach; ?>
            </div>

            <?php if (!empty($data['note'])) : ?>
                <p class="garmin-map-note"><?php echo esc_html((string) $data['note']); ?></p>
            <?php endif; ?>

            <footer class="garmin-map-footer">
                <span>Карты создаются проектом <strong>OSM Topo</strong> на основе данных OpenStreetMap.</span>
                <a class="garmin-github-btn"
                   href="<?php echo esc_url(URALLA_GARMIN_GITHUB_URL); ?>"
                   target="_blank"
                   rel="noopener noreferrer">
                    <svg viewBox="0 0 24 24" aria-hidden="true">
                        <path fill="currentColor" d="M12 .7a11.5 11.5 0 0 0-3.64 22.41c.58.11.79-.25.79-.56v-2.23c-3.22.7-3.9-1.37-3.9-1.37-.53-1.34-1.28-1.7-1.28-1.7-1.05-.72.08-.7.08-.7 1.16.08 1.77 1.19 1.77 1.19 1.03 1.77 2.7 1.26 3.36.96.1-.75.4-1.26.73-1.55-2.57-.29-5.27-1.28-5.27-5.69 0-1.26.45-2.29 1.19-3.09-.12-.29-.52-1.47.11-3.05 0 0 .97-.31 3.16 1.18a10.98 10.98 0 0 1 5.75 0c2.2-1.49 3.16-1.18 3.16-1.18.63 1.58.23 2.76.11 3.05.74.8 1.19 1.83 1.19 3.09 0 4.42-2.71 5.39-5.29 5.68.42.36.79 1.07.79 2.16v3.2c0 .31.21.68.8.56A11.5 11.5 0 0 0 12 .7Z"/>
                    </svg>
                    GitHub · OSM Topo
                </a>
            </footer>
        <?php endif; ?>
    </section>

    <style>
        .garmin-map-status {
            --gm-border: #d9dee5;
            --gm-muted: #687385;
            --gm-bg: #f7f9fb;
            --gm-button: #24292f;
            margin: 24px 0;
        }

        .garmin-map-status * {
            box-sizing: border-box;
        }

        .garmin-map-status-head {
            display: flex;
            align-items: flex-start;
            justify-content: space-between;
            gap: 24px;
            margin-bottom: 14px;
        }

        .garmin-map-status-head h2 {
            margin: 0 0 6px;
        }

        .garmin-map-status-head p,
        .garmin-map-generated,
        .garmin-map-note {
            color: var(--gm-muted);
        }

        .garmin-map-status-head p {
            margin: 0;
        }

        .garmin-map-generated {
            flex: 0 0 auto;
            text-align: right;
            font-size: 13px;
            line-height: 1.45;
        }

        .garmin-map-legend {
            display: flex;
            flex-wrap: wrap;
            gap: 8px 16px;
            margin: 14px 0 18px;
            font-size: 13px;
            color: var(--gm-muted);
        }

        .garmin-map-grid {
            display: grid;
            grid-template-columns: repeat(2, minmax(0, 1fr));
            gap: 12px;
        }

        .garmin-map-card {
            border: 1px solid var(--gm-border);
            border-radius: 12px;
            background: #fff;
            padding: 15px;
            box-shadow: 0 1px 2px rgba(0,0,0,.025);
        }

        .garmin-map-card-top {
            display: flex;
            align-items: flex-start;
            justify-content: space-between;
            gap: 14px;
        }

        .garmin-map-card h3 {
            margin: 0;
            font-size: 17px;
            line-height: 1.3;
        }

        .garmin-map-state {
            flex: 0 0 auto;
            white-space: nowrap;
            font-size: 13px;
            color: var(--gm-muted);
        }

        .garmin-map-meta {
            display: flex;
            flex-direction: column;
            gap: 3px;
            margin-top: 9px;
            color: var(--gm-muted);
            font-size: 13px;
        }

        .garmin-map-meta strong {
            color: inherit;
            font-weight: 600;
        }

        .garmin-map-recipe-warning {
            cursor: help;
            font-size: .9em;
        }

        .garmin-map-recipe-note {
            margin-top: 9px;
            padding: 7px 9px;
            border-radius: 7px;
            background: #fff7db;
            font-size: 12px;
            line-height: 1.4;
        }

        .garmin-map-actions {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
            margin-top: 13px;
        }

        .garmin-map-btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            min-height: 36px;
            padding: 7px 11px;
            border: 1px solid var(--gm-border);
            border-radius: 7px;
            background: var(--gm-bg);
            color: inherit;
            text-decoration: none !important;
            font-size: 13px;
            font-weight: 600;
            transition: background .15s ease, border-color .15s ease;
        }

        .garmin-map-btn:hover {
            background: #eef2f6;
            border-color: #c8ced7;
        }

        .garmin-map-btn.is-disabled {
            opacity: .45;
            cursor: default;
        }

        .garmin-map-note {
            margin: 14px 0 0;
            font-size: 12px;
            line-height: 1.45;
        }

        .garmin-map-footer {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 14px;
            margin-top: 18px;
            padding-top: 14px;
            border-top: 1px solid var(--gm-border);
            color: var(--gm-muted);
            font-size: 13px;
        }

        .garmin-github-btn {
            display: inline-flex;
            align-items: center;
            gap: 7px;
            flex: 0 0 auto;
            padding: 7px 10px;
            border-radius: 7px;
            background: var(--gm-button);
            color: #fff !important;
            text-decoration: none !important;
            font-weight: 600;
        }

        .garmin-github-btn svg {
            width: 17px;
            height: 17px;
        }

        .garmin-map-status-error {
            padding: 14px;
            border: 1px solid #e5c2c2;
            border-radius: 10px;
            background: #fff6f6;
        }

        @media (max-width: 760px) {
            .garmin-map-grid {
                grid-template-columns: 1fr;
            }

            .garmin-map-status-head,
            .garmin-map-footer {
                flex-direction: column;
            }

            .garmin-map-generated {
                text-align: left;
            }

            .garmin-map-card-top {
                flex-direction: column;
                gap: 6px;
            }
        }
    </style>
    <?php

    return ob_get_clean();
}

add_shortcode('garmin_map_status', 'uralla_garmin_map_status_shortcode');
